### ISSUE TITLE
[BUG] Text using Google Fonts loaded from assets briefly renders with a fallback font

### ISSUE THREAD

**Issue by doppio** [material-foundation/google-fonts-flutter#168] opened 2021-05-21 15:55 UTC
**Describe the bug**
When a Google font is loaded from the Flutter app's assets using this package, there is a slight delay, during which the text is rendered with a fallback font. The same delay is not experienced when loading the font directly from assets, without using the `google_fonts` package.

The result is content that jumps around when the page is first loaded, which doesn't look great.
Note: I've only tested this on web.

**To Reproduce**
1. Add a Google font to the Flutter project under a `google_fonts` asset folder
2. Add the `google_fonts` directory as an asset in `pubspec.yaml`
3. Display some text using `google_fonts` with the font placed in assets
4. Run the app
5. Notice that there is at least one frame where the text is rendered with the wrong font

Full sample project which demonstrates the issue:
[google_font_delay.zip](https://github.com/material-foundation/google-fonts-flutter/files/6523637/google_font_delay.zip)

**Expected behavior**
`google_fonts` should display text using the correct font immediately when loading from assets, like it does when loading from assets without using `google_fonts`.

**Include the contents of your `google_fonts` directory**
[google_fonts.zip](https://github.com/material-foundation/google-fonts-flutter/files/6523686/google_fonts.zip)

**Screenshots**
[Video](https://user-images.githubusercontent.com/1127641/119163653-729bfa80-ba10-11eb-9933-a4c478a7d02a.mov
)

Text before `google_fonts` loads the font:

<img width="920" alt="Screen Shot 2021-05-21 at 8 34 31 AM" src="https://user-images.githubusercontent.com/1127641/119163601-6748cf00-ba10-11eb-97ac-24ed8e4b3b2b.png">

Text after `google_fonts` loads the font:

<img width="919" alt="Screen Shot 2021-05-21 at 8 34 40 AM" src="https://user-images.githubusercontent.com/1127641/119163606-6879fc00-ba10-11eb-8f31-667d56c5ee63.png">

**Desktop (please complete the following information if applicable):**
 - OS: macOS Big Sur 11.2.3
 - Browser Chrome
 - Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by ayazthemre** [comment] 2021-07-15 22:46
Same here, also when something interferes while loading phase I get a long error on text_painter.dart file. While testing I need to wait a second for page to load or it freezes.

**Comment by madduruashok** [comment] 2021-07-28 10:45
Getting the same issue. 

Steps  followed:

-  Added _google_fonts: ^2.1.0_ in pubspec.yaml 
- Used fonts in textTheme
 `  textTheme: GoogleFonts.interTextTheme(Theme.of(context).textTheme)
         .apply(bodyColor: kContentColorLightTheme),`

FontSize is normal initially and increased after sometime.

**Comment by a-eniou-pvotal** [comment] 2022-04-20 00:01
any updates?

**Comment by guidezpl** [comment] 2022-05-20 11:14
There's is a very highly request FR that would solve this issue, so closing as duplicate of #151

**Closed by guidezpl** 2022-05-20 11:14 UTC
Labels: enhancement, help wanted
