### ISSUE TITLE
When LicenseRegistry.addLicense is entered, the Null check operator is displayed.

### ISSUE THREAD

**Issue by jtaxiexpress** [material-foundation/google-fonts-flutter#276] opened 2022-11-24 06:39 UTC
I used zenKakuGothicNew.

<img width="363" alt="スクリーンショット 2022-11-24 15 37 09" src="https://user-images.githubusercontent.com/86914073/203711381-c9ef991a-31a9-448a-8096-91bf916de2ac.png">

- main.dart
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await MobileAds.instance.initialize();
  await loadAd();

  LicenseRegistry.addLicense(() async* {
    final license = await rootBundle.loadString('google_fonts/OFL.txt');
    yield LicenseEntryWithLineBreaks(['google_fonts'], license);
  });

  runApp(const MyApp());
}
```

- home_screen.dart
```
  Future _showLicense(BuildContext context) async {
    PackageInfo packageInfo = await PackageInfo.fromPlatform();
    showAboutDialog(
      context: context,
      applicationName: packageInfo.appName,
      applicationVersion: packageInfo.version,
      applicationIcon: Icon(Icons.tag_faces),
      applicationLegalese: "Minerva K.K",
    );
  }
```
If commentout LicenseRegistry
I can open license screen.

<img width="363" alt="スクリーンショット 2022-11-24 15 38 13" src="https://user-images.githubusercontent.com/86914073/203711598-e48256a2-c941-4dfb-a8ca-3663ea639791.png">

**Comment by esouthren** [comment] 2022-11-30 11:47
Hi @jtaxiexpress, thanks for raising the issue. 

I've recreated your issue and the problem is that your code doesn't have the appropriate `OFL.txt` file included, which is the null error you are finding. 

Please follow the guidance in our docs, in particular the section on [Font bundling in assets](https://github.com/material-foundation/google-fonts-flutter#font-bundling-in-assets). Ensure the license text file is downloaded for your chosen font, and that it is included in your assets folder. 

I hope this helps - closing this issue for now. Thanks for using Google Fonts!

**Closed by esouthren** 2022-11-30 11:47 UTC
