### ISSUE TITLE
[BUG] TextOverFlow.elipsis not working as inteded for google fonts.

### ISSUE THREAD

**Issue by AryashDubey** [material-foundation/google-fonts-flutter#160] opened 2021-03-31 20:20 UTC
**Describe the bug**
I am using dmSans for my flutter web app but the textoverflow.elipsis is showing a ugly square in the end. This problem occurs only when using google fonts in a flutter web application and also this issue ONLY HAPPENS WITH CANVASKIT RENDERER.
**To Reproduce**
1. Use google fonts DM Sans in flutter web and make the text overflow
2. Use the Canvas Kit Renderer to run the app (IMPORTANT)

**Expected behavior**
Expected Behaviour should be ----> Signature...

**Screenshots**
![Screenshot 2021-04-01 014640](https://user-images.githubusercontent.com/70095055/113205987-863aa880-928c-11eb-8fca-a24a6aa5a983.png)

**Comment by bernaferrari** [comment] 2021-04-01 22:09
Isn't this a Flutter bug?

**Comment by rebooter1337** [comment] 2021-04-08 12:25
im having almost the same issue, but it occures only with Inter font
![image](https://user-images.githubusercontent.com/36457491/114026194-a36c0a00-987e-11eb-8fe8-327a6633dea7.png)

**Comment by akozin** [comment] 2021-05-26 13:24
I have faced with the same issue.
Are there any updates? 🤔

**Comment by johnsonmh** [comment] 2021-11-15 21:37
I made a reproducible example of this bug without the `google_fonts` package - I filed an issue to the flutter framework: https://github.com/flutter/flutter/issues/93685

**Comment by guidezpl** [comment] 2022-05-20 06:07
I'm going to close this since this is an upstream issue (https://github.com/flutter/flutter/issues/90135). Please continue the conversation there

**Closed by guidezpl** 2022-05-20 06:07 UTC
Labels: flutter framework bug
