### ISSUE TITLE
[BUG] Lato not displaying hungarian characters on Android

### ISSUE THREAD

**Issue by ervindobri** [material-foundation/google-fonts-flutter#198] opened 2021-11-29 13:50 UTC
**Describe the bug**
As title says: lato not displaying the special hungarian characters like ő,ű etc.  Instead it displays a ? - in a rectangle.

**To Reproduce**
1. Text widget with style as GoogleFonts.lato()
2. Display a character from this list: ő,ű
3. Observe that it isn't being displayed correctly. 

**Expected behavior**
Text should be displayed normally.

**Include the contents of your `google_fonts` directory**
Add contents here.

**Screenshots**
![image](https://user-images.githubusercontent.com/56959368/143879733-bd79a7c3-6323-4c3b-84a0-3bc764be4862.png)

**Desktop (please complete the following information if applicable):**
 - OS: Android
 - Both simulator & real device

**Smartphone (please complete the following information if applicable):**
- Multiple smartphones were tested

**Comment by guidezpl** [comment] 2021-12-30 13:13
Hi @ervindobri I'm unable to reproduce this with `2.2.0`
<img width="487" alt="Screen Shot 2021-12-30 at 14 12 25" src="https://user-images.githubusercontent.com/6655696/147755074-fd290e12-ef43-4009-946a-f2535e84a7b2.png">. Is it still occuring?

If so, please provide the output of `flutter doctor -v` and a relevant code sample

**Comment by ervindobri** [comment] 2022-01-10 10:22
'
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/ervindobri/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ervindobri/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • w1ntEr-phone (mobile)       • 28f2e50b9c124b29dc81f06dc4a701e038f8fb35 • ios            • iOS 14.5.1 18E212
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 1 category.
`

**Comment by ervindobri** [comment] 2022-01-10 10:23
dsadsaa

> 

I have the same issue with **bitter** font now... on android simulator, and few reports have been from android devices...

**Comment by guidezpl** [comment] 2022-01-10 11:20
Could you try a few things?

`flutter clean`
`flutter pub upgrade`

And copy the code sample used, as well as the output of `flutter run -v`

**Comment by ervindobri** [comment] 2022-01-15 09:11
I tried the solutions above, and flutter run -v didn't help either.
What's weird that this doesn't happen everywhere in a single device either. So it could be happening or not in different screens...

Ultimately the 'solution'/workaround  was to download & load the fonts from the assets since GoogleFonts.bitter... didn't work.

**Comment by guidezpl** [comment] 2022-01-17 13:37
Without output from `flutter run -v` or a code sample, it's difficult to debug.. Could you please provide those?

**Comment by guidezpl** [comment] 2022-05-20 07:43
Without a reproducible code sample, we're unfortunately not sure how to resolve this issue. I'm therefore reluctantly going to close this for now. Please don't hesitate to comment on the issue if you have any more information to add; we'll reopen it right away!

**Closed by guidezpl** 2022-05-20 07:43 UTC
Labels: bug, waiting for developer response
