### ISSUE TITLE
Rupee symbol is not supported

### ISSUE THREAD

**Issue by suvindran3** [material-foundation/google-fonts-flutter#192] opened 2021-10-16 06:34 UTC
I tried number of google fonts and I can't get any of them to display the Rupee symbol '₹' instead it's showing the Ruble symbol ' ₽'

**Comment by johnsonmh** [comment] 2021-11-15 20:43
I was not able to reproduce this. What fonts specifically didn't work? What device are you running on?

For example, with this snippet:

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const Scaffold(body: Body()),
    );
  }
}

class Body extends StatelessWidget {
  const Body({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text(
        '₹',
        style: GoogleFonts.lato(fontSize: 108),
      ),
    );
  }
}

```

I get this result when running on an iOS simulator

<img src="https://user-images.githubusercontent.com/4229329/141850471-7c8e8721-6ca9-4f93-8ef2-515727ca950b.png" width="300">

I had the same results with other fonts. In addition to Lato: Pacifico, Roboto, and Hind.

**Comment by guidezpl** [comment] 2022-05-20 07:42
Thank you for taking the time to file this issue. Without additional information, we're unfortunately not sure how to resolve this issue. I'm therefore reluctantly going to close this for now. Please don't hesitate to comment on the issue if you have any more information to add; we'll reopen it right away!

**Closed by guidezpl** 2022-05-20 07:42 UTC
Labels: bug, waiting for developer response

**Comment by Chinmay-KB** [comment] 2022-10-28 10:23
For anyone facing this issue, please note that this can be an issue with the font itself. For eg in futura, the same thing is happening
![image](https://user-images.githubusercontent.com/13520364/198565374-62eb43c2-c0ba-4783-9464-5d0fc6f60640.png)
