### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by amreniouinnovent** [material-foundation/google-fonts-flutter#12] opened 2019-12-12 06:08 UTC
I wonder if this plugin supports Flutter web?

**Comment by johnsonmh** [comment] 2019-12-13 16:44
Thanks for filing, it helps us to know that this is important to you. Right now there is an open issue with web support coming from the flutter framework. It does work, but on its first load, will not resize the text correctly. 

See https://github.com/flutter/flutter/issues/44460 for more details.

**Comment by leisim** [comment] 2020-01-09 11:27
@johnsonmh The issue is resolved now. Web support would be amazing :+1:

**Comment by hauketoenjes** [comment] 2020-01-15 00:32
The problem seems to be the path_provider package since it has no web support and will probably never get it for web. But i think it isn't very important to cache the fonts when dealing with a web app, right? I mean other websites load fonts when you open them.

Can that be done with the current code base? Or is there a problem when caching them also? It would at least be a great workaround so that the package can be used in web.

**Comment by leisim** [comment] 2020-01-15 08:19
> But i think it isn't very important to cache the fonts when dealing with a web app, right?

The browser already caches fonts if possible so I don't think any caching mechanism needs to be implemented.

**Comment by hauketoenjes** [comment] 2020-01-15 12:07
Ok, i looked a bit through the code and there is web support in this library, but it is not complete.

In Line 138 there is a checkt whether the code has been compiled to run on web or not. If not the `_loadFontFromDeviceFileSystem(familyWithVariantString)` will be skipped. That totally makes sense, because `path_provider` cannot return a path, if the client is a browser. 

The font is then being loaded from the web, but the function `_httpFetchFontAndSaveToDevice()` as the name already tells is trying to store the font on device using `path_provider`.

This is probably the problem. I'll test that in a seperate fork. 

https://github.com/material-foundation/google-fonts-flutter/blob/4d1eec014cb4730466973964543d9a263ad38a2d/lib/src/google_fonts_base.dart#L138-L147

**Comment by hauketoenjes** [comment] 2020-01-15 12:36
Ok, seems like it is not a problem with this library. There is also an issue mentioned in code

https://github.com/flutter/flutter/issues/44460

**Comment by hauketoenjes** [comment] 2020-01-16 16:31
I just upgraded Flutter to beta version `[✓] Flutter (Channel beta, v1.13.6, on Linux, locale de_DE.UTF-8)` and the issue seems to be resolved. It works with the current Version of Google Fonts (0.3.2).

![image](https://user-images.githubusercontent.com/25830076/72543280-ce3afe80-3885-11ea-80d2-b0fa5951749f.png)

**Comment by johnsonmh** [comment] 2020-01-21 19:35
Yes, this package does support flutter web! 

Just like this package, flutter web in general is in beta, please keep that in mind as you experiment with it. 

@leisim Is correct, `path_provider` does not support web, however, we don't need to use it because the browser caches the GET requests for the font files.

I'm going to close this issue, if you encounter flutter web specific font bugs, feel free to file them to here or directly to https://github.com/flutter/flutter/issues.

**Closed by johnsonmh** 2020-01-21 19:35 UTC

**Comment by xpat** [comment] 2020-01-28 20:18
I'm unable to get this to work.  I run flutter run -d chrome, or flutter build web.  It generates a new file .flutter-plugins-dependencies which reads: {"_info:"// This is a generated file; do not edit or check into version control.","dependencyGraph":[{"name":"path_provider","dependencies":[]}]}. 

I'm not sure what to make of the last comment @johnsonmh 
Do I remove it from my pubspec.yaml?

> @leisim Is correct, path_provider does not support web, however, we don't need to use it because the browser caches the GET requests for the font files.

**Comment by hauketoenjes** [comment] 2020-01-28 21:51
You are right that it is not working on your version. You should try upgrading. 

There is an issue referenced in the code that handles this problem. It has something to do with how flutter/dart renders fonts and I think it needs a specific system call that didn't work on web until the new version (cause the merge request was merged in the current release).
